---
# logging
logging: debug

# InfluxDB v2.x configuration
influxdb:
  server:
    - name: local
      url: http://172.18.0.2:8086
      org: snmptraps
      token: influx-snmptraps
      bucket: snmptraps

# Default Processing
all:
  measurement: snmptraps
  tags:
    host_dns: host_name
    host_ip: host_ip
    oid: oid

# Custom processing based on OID
mappings:
  IF-MIB::linkUp:
    measurement: link
    tags:
      - snmpTrapOID
      - ifIndex
      - ifName
    fields:
      - ifAdminStatus
      - ifOperStatus
  IF-MIB::linkDown:
    measurement: link
    tags:
      - snmpTrapOID
      - ifIndex
      - ifName
    fields:
      - ifAdminStatus
      - ifOperStatus