# Log Level
logging: ERROR

# Influx DB configuration
influxdb:
  server:
    - name: local
      url: https://127.0.0.1:8086
      org: org
      token: token
      bucket: bucket

# All traps process configuration
default_mapping:
  measurement: snmptraps
  tags:
    host_dns: host_name
    host_ip: host_ip
    oid: oid

# Custom traps process configuration
custom_mappings:
  IF-MIB::linkUp:
    measurement: link
    tags:
      - snmpTrapOID
      - ifIndex
      - ifName
    fields:
      - ifAdminStatus
      - ifOperStatus
  IF-MIB::linkDown:
    measurement: link
    tags:
      - snmpTrapOID
      - ifIndex
      - ifName
    fields:
      - ifAdminStatus
      - ifOperStatus
# Mibs
mib_list: ['SNMPv2-MIB']

# SNMPv2
snmpv2:
  - community: public
    description: default

# SNMPv3
snmpv3:
  engine_id: 800009e5604083371bc6d10a42
  users:
    - user: usr-md5-aes128
      auth_protocol: md5
      auth_key: authkey1
      priv_protocol: aes128
      priv_key: privkey1
